version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gulp-replace
    versions:
    - 1.0.0
    - 1.1.0
    - 1.1.1
  - dependency-name: lodash
    versions:
    - 4.17.20
